# PART1 簡単な予測モデルを作ってみよう

## おまじない

In [135]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression as LR

## データの読み込み
- train.csvとtest.csvとsample.csvの３つのファイルを読み込みましょう
- それぞれを読み込んだものは変数はtrain, test, sampleに代入しましょう
- sampleを読み込む時は、header=Noneというオプションを忘れないようにしましょう

In [171]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
sample = pd.read_csv("sample.csv",header=None)

## trainの先頭行を見てみましょう

In [172]:
train.head()

datetime    y week  soldout        name  kcal remarks event  payday  \
0  2013-11-18   90    月        0    厚切りイカフライ   NaN     NaN   NaN     NaN   
1  2013-11-19  101    火        1     手作りヒレカツ   NaN     NaN   NaN     NaN   
2  2013-11-20  118    水        0  白身魚唐揚げ野菜あん   NaN     NaN   NaN     NaN   
3  2013-11-21  120    木        1      若鶏ピリ辛焼   NaN     NaN   NaN     NaN   
4  2013-11-22  130    金        1    ビッグメンチカツ   NaN     NaN   NaN     NaN   

  weather precipitation  temperature  
0      快晴            --         19.8  
1      快晴            --         17.0  
2      快晴            --         15.5  
3      快晴            --         15.2  
4      快晴            --         16.1

## trainから説明変数と目的変数となるデータを取り出しましょう
- 説明変数はtrainからtemperatureを選択し、変数名をtrainXとして代入しましょう
- 目的変数はtrainからyを選択し、変数名をyとして代入しましょう

In [173]:
trainX = train["temperature"]
y = train["y"]

## testから説明変数となるデータを取り出しましょう
- 説明変数はtrainと同じtemperatureを選択し、変数名をtestXとして代入しましょう

In [174]:
testX = test["temperature"]

## 単回帰の場合のみ、説明変数に対しておまじないが必要となります
- 単回帰の場合はややこしいですが、train,testの説明変数ともに、データの形を整える必要があります
- 具体的にはvalues.reshape(-1,1)というおまじないをします
- 整えた後、再び変数Xに代入します

In [175]:
trainX = trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

## 回帰のモデルの箱を用意しましょう
- モデルを作る為にはまず、モデルを表す箱が必ず必要になります
- 変数名をmodel1として、LR()を代入しましょう

In [176]:
model1 = LR()

## 単回帰モデルを作りましょう
- fit関数を使います
- カッコの中に、説明変数、目的変数の順番に書きます

In [177]:
model1.fit(trainX,y)
##「fit」で単回帰。説明変数が先。

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

## 作ったモデルの傾きや切片を確かめてみましょう
- 傾きはcoef_を使います
- 切片はintercept_を使います

In [178]:
model1.coef_

array([-2.5023821])

In [179]:
model1.intercept_

134.79948383749922

## 予測をしましょう
- predict関数を使います
- 予測結果は変数predに代入しましょう

In [180]:
pred = model1.predict(testX)

In [181]:
pred

array([  84.25136537,   74.99255159,   62.9811175 ,   80.99826864,
         79.49683938,   76.49398085,   78.49588653,   69.48731097,
         67.73564349,   95.76232304,   88.25517673,   77.24469548,
         74.99255159,   84.25136537,   96.01256125,   98.01446693,
         88.00493852,   77.99541011,   87.00398568,   85.75279463,
         85.75279463,   87.75470031,   87.5044621 ,   94.7613702 ,
         86.75374747,   84.50160358,   81.74898327,   98.01446693,
         98.76518156,   86.00303284,   95.26184662,   99.01541977,
         94.51113199,   97.51399051,  108.52447176,   97.51399051,
        106.27232787,  111.7775685 ,   97.01351409,   96.51303767])

## sampleの中身を確認してみましょう

In [182]:
sample.head()

0   1
0  2014-10-1  24
1  2014-10-2  71
2  2014-10-3  25
3  2014-10-6  32
4  2014-10-7  60

## sample[1]に予測結果を代入しましょう

In [183]:
sample[1] = pred
##1列目を消して上書きする。
##2にすると2列目に並べる。

In [184]:
sample.head()

0          1
0  2014-10-1  84.251365
1  2014-10-2  74.992552
2  2014-10-3  62.981117
3  2014-10-6  80.998269
4  2014-10-7  79.496839

## sampleをファイルで書きだしましょう
- to_csv関数を使います
- オプションは３つあり、"submit1.csv", index=None, header=Noneを書きます

In [185]:
sample.to_csv("submit1.csv",index=None,header=None)

# 実習
1.説明変数をkcalとして、単回帰モデルを作ろう。まず、 trainとtestのkcalに欠損値があるかないか確認しよう
- 本当に欠損があるかどうか、head関数を使って確認しよう

In [186]:
train.isnull().sum()
##isnullで欠損値かどうか
##sum()でその合計

datetime           0
y                  0
week               0
soldout            0
name               0
kcal              41
remarks          186
event            193
payday           197
weather            0
precipitation      0
temperature        0
dtype: int64

In [187]:
test.isnull().sum()

datetime          0
week              0
soldout           0
name              0
kcal              4
remarks          33
event            37
payday           38
weather           0
precipitation     0
temperature       0
dtype: int64

2.trainのkcalの平均値を求め、変数avgに代入しよう

In [188]:
avg = train["kcal"].mean()

In [189]:
avg

404.4096385542169

3.変数avgを使って、trainとtestのkcalの欠損値を補間し、それぞれを変数名trainXとtestXに代入してみよう

In [190]:
trainX = train["kcal"].fillna(avg)
testX = test["kcal"].fillna(avg)

4.trainXとtestXをvalues.reshape(-1,1)を使って形を整え、再びtrainX, testXへ代入しよう
    1. 3番ではtrainXにはavgで補間されたtrain["kcal"]が代入される
    2. 4番では補間されたtrainXにおまじないをかけたものがtrainXに代入されることになる

In [191]:
trainX = trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

5.trainからyを取り出し、変数yに代入しよう

In [192]:
y = train["y"]

6.回帰モデルの箱を変数名model2として用意しよう

In [193]:
model2 = LR()
##回帰モデルのオブジェクトを作り、そこに「LR()」を代入する
##回帰をするときは、オブジェクト（model2）に関数を付ける

7.trainXとyを使って単回帰のモデルを作ろう

In [194]:
model2.fit(trainX,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

8.作ったモデルの傾きと切片を確認しよう

In [195]:
model2.coef_

array([ 0.13195178])

In [196]:
model2.intercept_

33.260615770294407

9.testXを使って予測をし、予測値を変数pred2に代入しよう

In [197]:
pred2 = model2.predict(testX)

10.sample[1]にpred2を代入しよう

In [198]:
sample[1] = pred2

In [199]:
sample

0          1
0    2014-10-1  88.680364
1    2014-10-2  88.020605
2    2014-10-3  86.701088
3    2014-10-6  86.041329
4    2014-10-7  89.999882
5    2014-10-8  88.680364
6    2014-10-9  90.659641
7   2014-10-10  86.623188
8   2014-10-14  87.096943
9   2014-10-15  92.638918
10  2014-10-16  86.041329
11  2014-10-17  88.020605
12  2014-10-20  89.472075
13  2014-10-21  87.360847
14  2014-10-22  88.020605
15  2014-10-23  89.735979
16  2014-10-24  86.623188
17  2014-10-27  86.964991
18  2014-10-28  89.340123
19  2014-10-29  89.999882
20  2014-10-30  89.472075
21  2014-10-31  90.791593
22   2014-11-4  91.319400
23   2014-11-5  89.340123
24   2014-11-6  87.360847
25   2014-11-7  86.623188
26  2014-11-10  87.624750
27  2014-11-11  89.472075
28  2014-11-12  88.416461
29  2014-11-13  85.513522
30  2014-11-14  89.604027
31  2014-11-17  90.395738
32  2014-11-18  87.228895
33  2014-11-19  89.999882
34  2014-11-20  88.812316
35  2014-11-21  86.623188
36  2014-11-25  93.958436
37  2014-11-26  88.020605
38  2014-11-27  88.680364
39  2014-11-28  88.152557

11.to_csv関数のindex=Noneがある時とない時の違い、header=Noneがある時とない時の違いは何かを考えてみよう

In [200]:
##「index」は一番左の行番号。

12.sampleをファイル出力し、submit2.csvという投稿用ファイルを作ろう

In [201]:
sample.to_csv("submit2.csv",index=None,header=None)
##「to_csv()」関数でオブジェクトにあるデータフレームをcsv形式で保存


13.submit2.csvをDeepAnalyticsに投稿して、submit1.csvのスコアを比較してみよう